import { Router } from 'express';
import authRoutes from './auth.routes.js';
import organizationRoutes from './organization.routes.js';
import assetRoutes from './asset.routes.js';
import healthRoutes from './health.routes.js';
import mspRoutes from './msp.routes.js';
import apikeyRoutes from './apikey.routes.js';
import webhookRoutes from './webhook.routes.js';
import scanRoutes from './scan.routes.js';
import vulnerabilityRoutes from './vulnerability.routes.js';
import monitoringRoutes from './monitoring.routes.js';
import cloudConnectorRoutes from './cloud_connector.routes.js';
import eventRoutes from './event.routes.js';
import detectionRoutes from './detection.routes.js';
import graphRoutes from './graph.routes.js';
import riskRoutes from './risk.routes.js';
import incidentRoutes from './incident.routes.js';
import sentinelAiRoutes from './sentinel_ai.routes.js';
import autopilotRoutes from './autopilot.routes.js';
import remediationRoutes from './remediation.routes.js';
import recoveryRoutes from './recovery.routes.js';
import threatIntelRoutes from './threat_intel.routes.js';
import complianceRoutes from './compliance.routes.js';
import siemRoutes from './siem.routes.js';
import soarRoutes from './soar.routes.js';
import deceptionRoutes from './deception.routes.js';
import microsegmentationRoutes from './microsegmentation.routes.js';
import identityRoutes from './identity.routes.js';
import finopsRoutes from './finops.routes.js';
import brandProtectionRoutes from './brand_protection.routes.js';
import executiveReportingRoutes from './executive_reporting.routes.js';
import subscriptionRoutes from './subscription.routes.js';
import mobileSecurityRoutes from './mobile_security.routes.js';
import edgeSecurityRoutes from './edge_security.routes.js';
import selfHealingRoutes from './self_healing.routes.js';
import threatExchangeRoutes from './threat_exchange.routes.js';
import aiInvestigationRoutes from './ai_investigation.routes.js';
import masteryBenchmarkRoutes from './mastery_benchmark.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/organizations', organizationRoutes);
router.use('/assets', assetRoutes);
router.use('/msp', mspRoutes);
router.use('/api-keys', apikeyRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/scans', scanRoutes);
router.use('/vulnerabilities', vulnerabilityRoutes);
router.use('/monitoring', monitoringRoutes);
router.use('/cloud-connectors', cloudConnectorRoutes);
router.use('/events', eventRoutes);
router.use('/detection', detectionRoutes);
router.use('/graph', graphRoutes);
router.use('/risk', riskRoutes);
router.use('/incidents', incidentRoutes);
router.use('/sentinel-ai', sentinelAiRoutes);
router.use('/ai', sentinelAiRoutes);
router.use('/autopilot', autopilotRoutes);
router.use('/remediation', remediationRoutes);
router.use('/recovery', recoveryRoutes);
router.use('/threat-intel', threatIntelRoutes);
router.use('/compliance', complianceRoutes);
router.use('/siem', siemRoutes);
router.use('/soar', soarRoutes);
router.use('/deception', deceptionRoutes);
router.use('/microsegmentation', microsegmentationRoutes);
router.use('/identity', identityRoutes);
router.use('/finops', finopsRoutes);
router.use('/brand-protection', brandProtectionRoutes);
router.use('/executive-reports', executiveReportingRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/mobile-security', mobileSecurityRoutes);
router.use('/edge-security', edgeSecurityRoutes);
router.use('/self-healing', selfHealingRoutes);
router.use('/threat-exchange', threatExchangeRoutes);
router.use('/ai-investigations', aiInvestigationRoutes);
router.use('/mastery-benchmark', masteryBenchmarkRoutes);

export default router;
